export const KURIR_MASTER = [
  { kode: "jne", nama: "JNE" },
  { kode: "pos", nama: "POS Indonesia" },
  { kode: "tiki", nama: "TIKI" },
  { kode: "jnt", nama: "J&T Express" },
  { kode: "sicepat", nama: "SiCepat" },
  { kode: "anteraja", nama: "AnterAja" },
  { kode: "ninja", nama: "Ninja Xpress" },
  { kode: "lion", nama: "Lion Parcel" },
  { kode: "ide", nama: "ID Express" },
  { kode: "sap", nama: "SAP Express" },
  { kode: "ncs", nama: "Nusantara Card Semesta (NCS)" },
  { kode: "rex", nama: "Royal Express Indonesia (REX)" },
  { kode: "rpx", nama: "RPX" },
  { kode: "sentral", nama: "Sentral Cargo" },
  { kode: "star", nama: "Star Cargo" },
  { kode: "wahana", nama: "Wahana Ekspedisi" },
  { kode: "dse", nama: "21 Express (DSE)" },
] as const;